[package]
name        = "ring-pwhash"
version     = "0.1.2"
description = "A collection of password hashing functions, using *ring* cryptographic primitives"
authors     = ["Tony Arcieri <bascule@gmail.com>", "The Rust-Crypto Project Developers"]
homepage    = "https://github.com/cryptosphere/ring-pwhash"
repository  = "https://github.com/cryptosphere/ring-pwhash"
license     = "MIT/Apache-2.0"
readme      = "README.md"
keywords    = ["password", "scrypt", "ring"]
categories  = ["authentication", "cryptography"]

[lib]
name = "ring_pwhash"

[dependencies]
crossbeam = "0.2"
libc = "^0.2"
rustc-serialize = "^0.3"
ring = ">= 0.2"
